version: 0.0
os: linux
files:
  - source: /dist/
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: scripts/stop_httpd.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/undeploy_oldfiles.sh 
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_httpd.sh
      timeout: 300
      runas: root
